### ISSUE TITLE
Unsecure money receiver - receive only mode

### ISSUE THREAD

**Issue by adattudos** [voisine/breadwallet#102]
To provide even higher level of security breadwallet could support receive only mode.
BIP32 CKD functions enable to derive public child keys from public parent keys.
Breadwallet should support importing public parent keys and be used as a watch and receive only HD wallet. Alternatively there would be an (advanced) option to disable spending and forget the private keys after the export of the backup phrase.

The receive only HD breadwallet would provide ultimate mobile bitcoin wallet security.
Such feature is not available in mobile HD wallets, yet.

**Comment by Levino** [comment]
@voisine So, Bitcoin Wallet on Android, Mycelium, Trezor, Electrum and Armory support the export of the public seed data. Are you still thinking that this is an unnecessary / dangerous feature? Our customers are unhappy because they cant connect your software with coyno.

**Comment by dabura667** [comment]
@Levino
http://bip32jp.github.io/english/
1. insert mnemonic phrase
2. change "custom path" to `m/0'`
3. Copy xpub from "Derived Public Key" box.

This can be done offline by downloading from github. Link is on the site.

Not optimal, but if your customers are so unhappy, I'm sure they wouldn't mind unplugging their internet for a second to generate the xpub.

**Comment by Levino** [comment]
Thanks @dabura667 this might be a good workaround. Havent thought of that...

**Comment by voisine** [comment]
@Levino, I'd much rather export a list of bitcoin addresses than the xpub. I'm not a cryptographer but my understanding is that the issue of a single private key compromising the whole wallet wouldn't be possible from just a list of addresses. Also users would still have the possibility of privacy going forward if the list were compromised.

**Comment by voisine** [comment]
@dabura667, unplugging Internet doesn't protect you. A key logger can just wait til you connect again.

**Comment by keo** [comment]
Don't understand the use case where a single private key would leak besides the xpub (and not the passphrase).

Can you elaborate? Maybe i'm missing something.

**Comment by voisine** [comment]
@keo, it's not very likely but there are several possible scenarios where individual private keys could be compromised while the master wallet seed is not. There are em-side channel attacks on the hardware itself, the possibility of implementation errors in the ecdsa signing (this famously happened to blockchain.info recently), attacks involving other apps running in the background and the CPU cache: https://eprint.iacr.org/2014/140.pdf

Then there's also the very remote possibility of a weakness in ecdsa itself being discovered. In which case wallet funds would still be secure if they're not on re-used addresses that have their pubkey exposed. With your xpub floating around, then your entire wallet is exposed at the same level as a re-used address.

**Comment by rgenito** [comment]
Nice.

**Comment by Levino** [comment]
@voisine This might be possible, but as you said it is very unlikely. Also I heavily doubt that people will store huge amounts on your wallet. If they do then they are not caring about security in the first place. The most realistic scenario for a compromised private key is in my opinion the possibility that all the users data is synced to the Apple headquartes in the background for thorough inspection by the NSA. So while we are discussing very rare and sophisticated attacks (if someone runs an EM sidechannel attack on your iPhone you are in more trouble than losing a couple of bitcents), other wallet designers just provide a solution for the needs of the users. What you are proposing is in my opinion "security through obscurity". I find that a warning "do not share with untrusted parties" etc. should be sufficient for the time being. As a user I care for "owning my device" and "owning my software".

**Comment by dabura667** [comment]
@voisine @Levino I am working on a new HD wallet derivation method that does not have the 1 child privkey + 1 parent pubkey = the parent privkey weakness.

I will probably post on bitcointalk once I work out the details, get a python implementation up on github, and place a bounty in index 1 and release the parent xpub and index 2 privkey to see if anyone can crack it... My wife is telling me not to do the bounty tho... so...

But yeah, BIP32's gotcha is a pretty big one... "OMG YOU CAN DO ALL THESE COOL THINGS ONLY WITH THE PUBKEYS OMGOMG"....... "BUT WAIT... not really safe lol"

~~Similar to BIP39's gotcha: "Seed generation is based off hashing, so no need to know the wordlist YAAAAAAY!!!!... BUT WAIT, you need to know the indices of each word in the wordlist to check the checksum lol~~

**Comment by voisine** [comment]
@Levino the intention is to make breadwallet the safest mobile wallet available. Much safer than hosted wallet solutions, none of which insure users funds against theft when connecting with an infected device. I am working under the assumption that people will put their entire life's savings in breadwallet since it's safer than the solutions many are already using to do this, not to mention more convenient.

Data synced to apples servers is strongly encrypted to a key fabbed into the device so useless without the device to decrypt it.

I disagree that there is any security through obscurity here. The code is public and open to all for inspection.

**Comment by voisine** [comment]
@dabura667 let me know when you have the spec ready.

**Comment by voisine** [comment]
I am thinking right now that implementing adress list export will improve security by reducing the number of people who type their recovery phrase into a desktop or web tool to get their xpub.

**Comment by Levino** [comment]
@voisine Exporting an export for a list of addresses wont do, because then permanent updates of the new addresses are needed. As you said people will use other tools like the above mentioned and some of them might use the wrong one and loose their coins. So maybe you are not increasing the security in the end.

As a second remark: A wallet on a closed source device such as the iPhone can never be secure. If "the most secure wallet" is your plan you should rather go for a open source hardware device like trezor does.

**Comment by voisine** [comment]
@Levino you would just export the list at the time you need it for something outside the wallet.

At a fundamental level, you will always have to trust the manufacturer of any electronic device. Even if the firmware is open source and you flash it yourself, you're not going to be able to examine the hardware it runs on. I do agree however that simpler devices with fewer components made by fewer manufacturers reduces the attack surface.

The problem is that customers care only about convenience, not security, so they are going to use their phones to manage their bitcoin. There's nothing we can do about that. So that's why I want to build the safest mobile wallet we possibly can on the devices people are actually going to use. That means iPhone and Android. iPhone is a lot easier to get acceptable levels of security with, so we're starting there.

**Comment by Levino** [comment]
Here, this was what I was looking for: http://www.tomsguide.com/us/apple-ntp-patch,news-20057.html It means Apple can push arbitrary code changes to its customers. Like "upload all data unencrypted to pastebin.com".

@dabura667 Thanks for your work. But this new algorithm sounds like a new BIP for me. I don't want to wait for it AND people will still have wallets in the old style, that need to be imported even if the wallets are meanwhile empty.

So far we will make a guide for our users to get the xpubkey out of the mnemonic and ask them to express their opinion publicly about whether or not they would like the feature in BreadWallet.

**Comment by voisine** [comment]
@Levino I'd like to figure out how we can work together for a safer solution than exporting the xpub. I know exporting an address list is less convenient, but maybe it could be automated with a url where the user expressly authorizes the request in breadwallet when they use coyno or other services. This would be an improvement of both security and forward looking privacy.

**Comment by Levino** [comment]
@voisine This sounds like a very promising approach. We are also talking to Andreas from Mycelium and Andreas from Bitcoin Wallet (on Android) about a "permanent link" to also share meta data put into the app by the user (like the exact exchange rate set for the calculation of the amount in the transfer). The communication and identification should be ensured by the signatures / encryption with the private key. We should definitely work together to find some kind of "reporting protocol" that sets up an initial sync and continues to do so later. I think the transfer of the public root seed is anyhow needed, but would be much safer than sharing it by email or so. This is of course a better approach.

That being said it will probably take us a while to figure out all the nuts and bolts for this protocol to be also open source, so that other services besides coyno can use the same functionality. Meanwhile I would love to go for the somewhat uncomfortable but already doable way of manually transferring the xpub. I will keep you posted on any progress we make in the direction of "secure linking" with auth / encr. by bitcoin keys.

**Comment by dabura667** [comment]
@voisine https://gist.github.com/dabura667/875bb2c159b219c18885

**Comment by dabura667** [comment]
it's basically the same thing as http://fc15.ifca.ai/preproceedings/paper_15.pdf this except only using 2 keys to protect against 1 leak.

Then just using conventions to prevent dangerous deriving practices.

**Comment by voisine** [comment]
@dabura667 this is very cool. I could implement this, but I'm not qualified to comment on the cryptography. Are you thinking of turning it into a BIP for further comment by other real cryptographers?

**Comment by dabura667** [comment]
How would I go about receiving a BIP number?

**Comment by voisine** [comment]
Post on the bitcoin development list to get feedback. I believe g.maxwell assigns bip numbers.

https://lists.sourceforge.net/lists/listinfo/bitcoin-development

**Comment by voisine** [comment]
@Levino I'm thinking about your use case, and the annoyance of having to export address lists each time. From the user's perspective, the important thing is the ability to revoke read access to the wallet whenever they wish. Obviously in that case anything already read can't be unread, but it would allow privacy from that point going forward.

Exporting a list of addresses has the effect of granting read access, and then automatically revoking it again, which is also sub-optimal if that's not what the user wants to do. I don't have a solution I like for this yet. There might be an option with allowing users to switch to a new address chain after giving out their xpub to "revoke read access", but that would still suffer from the individual private key leak problem outside implementing a different HD scheme entirely like the one dabura667 proposed.

**Comment by Levino** [comment]
@voisine To revoke read access, the user could just switch to another hardened chain. And this is not a very unrealistic scenario. If your pgp key gets compromised you also just make a new one...

**Comment by voisine** [comment]
@Levino with the new app store release you can export an address list for the wallet by loading bread://addresslist on the phone.

**Comment by Levino** [comment]
@voisine Thanks a lot! Will try it asap.

**Comment by dabura667** [comment]
Try tapping this in your browser on your iPhone. [bread://addresslist](bread://addresslist)

**Comment by Onetallnerd** [comment]
Thanks for bread://addresslist ! Nice little hidden feature.

**Comment by voisine** [comment]
@Onetallnerd thanks, I feel like being able to get your data out is important, but at the same time I don't want users to inadvertently weaken their security or lose their forward looking privacy. And being a url command, it doesn't clutter the UI with extra confusing options.

**Comment by voisine** [comment]
You can now paste a list of bitcoin addresses into the recover wallet dialog instead of a recovery phrase to create a watch-only wallet.

**Comment by rgenito** [comment]
sweeet!!
