### ISSUE TITLE
PIN storage enhancements

### ISSUE THREAD

**Issue by hubert3** [voisine/breadwallet#134]
Rather than storing the 4 digits of the PIN in Keychain as a plaintext value, it would be more secure to store a hash of the PIN using a slow hash function like bcrypt or scrypt.

A variable work factor could be used according to the speed of the device, so that hashing the PIN the user enters would take 0.5 - 1 second.

This would mean an attacker who's dumped keychain contents is not immediately able to recover the plaintext PIN value and it would take a couple of hours on average.

**Comment by voisine** [comment]
pin codes are trivial to crack even with the slowest of hashes. The safety of a pin relies on secure hardware that can enforce a limited number of failed attempts.

**Comment by voisine** [comment]
Since a pin is pretty much the opposite of cryptographically secure, it's not used for encrypting anything. Better to avoid security theater so no one is under false assumptions of greater security than they actually have

**Comment by hubert3** [comment]
Ok, since it's called the 'wallet PIN' I assumed the correct PIN was actually needed to decrypt my wallet and that it wasn't just unlocking the UI. TIL.

With a 4 digit PIN, assuming a slow hash that takes 1 second per attempt it would buy you at least 90 minutes on average, and require a more sophisticated attempt that brute forces the PIN, rather than just being able to dump everything in the background.

Is there any plan to allow for longer PINs or passwords that actually encrypt the user's keys?

**Comment by voisine** [comment]
You can't dump in the background without jailbreaking the device. Also offline cracking on desktop hardware would easily reduce the time to just a few minutes or less.

Allowing up to a 6 digit pin is something I'm thinking of adding. I'm more concerned about losses from forgotten pins/passwords though, since no password no matter how secure will protect you from a security compromised device.

**Comment by hubert3** [comment]
It's true that dumping keychain requires the device to be jailbroken, but Breadwallet running on knowingly jailbroken devices is not the only scenario to consider.

Jailbreakme.com back in 2011 jailbroke iOS 4.3 by chaining a few exploits which were triggered by a single tap in Mobile Safari. Given that numerous public jailbreaks for iOS 8 have been released, I think it's quite likely that private remote exploits also exist. The current scheme of storing everything in keychain without any encryption on top means a successful driveby or other remote attack could immediately steal Breadwallet private keys.

As someone who is currently trusting Breadwallet with over $3k, it doesn't make me feel very good that the wallet PIN is purely a UI thing, and that the app is 100% reliant on iOS and keychain not being compromised to keep the coins safe.

I'd feel more secure if there was the option to set up a longer PIN or passcode that actually encrypts my wallet. The backup phrase could still be displayed unencrypted to protect against losses. 

I do think that the Touch ID / Secure Enclave-based user presence keychain access policy provides a real additional benefit when considering this kind of scenario, as it makes it very obvious if anything tries to access sensitive keychain items.

Forcing the user to re-enter the device passcode or provide a fingerprint in order to unlock a credential, and having this enforced by hardware is the highest level of security currently available on the platform, and seems like a really good security feature to have, and IMO cryptocurrency wallets and banking apps ought to start using it.

**Comment by voisine** [comment]
@hubert3 I appreciate where you're coming from. The problem is that there's no good way to protect a wallet on a jailbroken device. Even if it's password encrypted, the malware can simply log keystrokes when you type it into the compromised device. Also as I pointed out, it's trivial to wait for the user to authorize a spend so they are not alerted to the malware stealing their seed.

Relying on the keychain and secure enclave actually is the right approach. On iOS 8 and above, the keychain is encrypted by the secure enclave. Apple claims it's secure in the event of a kernel compromise, and my own testing suggests that it gets wiped during a jailbreak, at least with currently known jailbreak exploits.

**Comment by dabura667** [comment]
> my own testing suggests that it gets wiped during a jailbreak, at least with currently known jailbreak exploits.

I can also corroborate this information. I tried jailbreaking one of my devices and breadwallet could no longer access its seed.

**Comment by hubert3** [comment]
Jailbreaking does not wipe keychain. If that were the case, all the recent iOS jailbreaks (Pangu, TAiG etc) would break a lot of things such as iMessage and the App Store which all store secrets in keychain. The fact that these all continue working without issues proves that keychain contents do not get wiped.

As far as I understand, only items with the flag kSecAccessControlUserPresence are protected by Secure Enclave (decrypting them requires a key which is only released from the enclave upon successful fingerprint or passcode auth).

Even then, jailbreaking does not automaticallty wipe these items, it just means that those items can't be dumped without authenticating every time you attempt to SecItemCopy one of the items.

I will install Breadwallet on a non-jailbroken iPhone 5s when I get back to work on Monday, jailbreak it and report it back.

**Comment by voisine** [comment]
@hubert3 appreciate the extra testing. I believe any service storing secrets will get signed out after a jailbreak, but not sure If that's a quirk of the specific jailbreak or a security feature of secure enclave at this point. You may also be correct that different keychain access settings have different behavior. iCloud keychian items may be resorted after signing into iCloud. Breadwallet doesn't use iCloud keychain.

**Comment by JustinDrake** [comment]
> On iOS 8 and above, the keychain is encrypted by the secure enclave.

@voisine Do you know which iOS 8 compatible iPhone models have the hardware secure enclave? I.e., which of the iPhones 4S, 5, 5C, 5S, 6 and 6 Plus have the secure enclave?

Do you prevent Breadwallet from installing on iPhone devices without the secure enclave?

**Comment by voisine** [comment]
@JustinDrake any model with touchid has it. It's part of the a7 chip. We don't prevent earlier phones, but we do require ios7 which has significant security upgrades over ios6. We'll be aggressive about increasing security requirements to the greatest degree practical.

**Comment by JustinDrake** [comment]
@voisine Understood. So Breadwallet users on an iPhone 4, 4S, 5 or 5C are not protected by the secure enclave. So the claim

> breadwallet is designed to protect you from [...] physical theft

does *not* hold true for iPhones 5C and below. It might be worth clarifying this in the documentation.

**Comment by voisine** [comment]
@JustinDrake Even without the secure enclave, all iOS devices breadwallet supports have full file system hardware encryption by default using a key that is fabbed into the phone. You can read about it in the iOS security whitepaper: https://www.apple.com/privacy/docs/iOS_Security_Guide_Oct_2014.pdf

**Comment by DavidStaron** [comment]
@voisine 
> The problem is that there's no good way to protect a wallet on a jailbroken device. Even if it's password encrypted, the malware can simply log keystrokes when you type it into the compromised device.

Agreed, but i think there might be another good reason to allow using longer passwords, example:
My iPhone is **not** jailbroken and i transfer some money to my Breadwallet wallet.
Then at some point, someone steals my iPhone, jailbreaks my device, cracks the 4 digit (easy brute forced) Breadwallet password. Now they have access to all my Bitcoins.

If my wallet would have been protected by a more complicated passphrase, they would first have to crack that passphrase, which might be impossible if the passphrase is strong enough, thus protecting my wallet?

**Comment by voisine** [comment]
@DavidStaron that is a fair point, and worth considering. However, ultimately the goal is to reduce bitcoin loss to the absolute minimum.

We must also consider the situation where a user doesn't write down their recovery phrase and then forgets their password. Users have been trained for years to rely on a "forgot your password" button.

Between that and the fact that current known jailbreak exploits wipe the keychain in the process makes me think that enabling longer passwords will result in more bitcoin loss, not to mention reducing usability. Entering passwords on mobile devices just plain sucks. We want something that's incredibly safe as well as easy and convenient. A short pin enforced by a hardened mobile device is ideal. Passwords are hard to remember, hard to use, and typically low entropy when used for encryption.

**Comment by DavidStaron** [comment]
@voisine okay i agree, but i think it might be better to make the 'simple passcode' the **default**, and provide an option to enable a stronger password - most regular users don't even care to look in the advanced options.
This is what Apple does in iOS as well, and it works there. Loosing your iOS passcode also means loosing all data on your device. It's the users own responsibility to choose what they want/need.

**Comment by hubert3** [comment]
@voisine, @JustinDrake - I carried out an experiment to test whether the Secure Enclave on the iPhone 5s really protects keychain and causes it to be wiped when you jailbreak as was suggested above.

Test setup: iPhone 5s 16 GB on iOS 8.1, never jailbroken, screen lock PIN and Touch ID enabled.

About a month ago, I installed Breadwallet 0.5 from the App Store, generated a new wallet, set a 4-digit Breadwallet PIN, noted down the recovery phrase, etc.

Today I ran the TaiG Jailbreak Tool v1.2.1 from http://www.taig.com/en which successfully installed Cydia on the device. I installed OpenSSH in Cydia and ssh'd into the iPhone with the root:alpine account.

I then compiled the keychain_dump utility from https://code.google.com/p/iphone-dataprotection/source/browse/?repo=keychainviewer on my Mac and ran it on the iPhone:

# ./keychain_dump
Writing 59 passwords to genp.plist
Writing 1 internet passwords to inet.plist
Writing 7 certificates to cert.plist
Writing 26 keys to keys.plist

As expected, the **genp.plist** file contains all of Breadwallet's secrets, including the 4-digit PIN, the recovery phrase and the master public key visible in plain text. NB: This is a test phone and I never kept any bitcoins in this wallet:

                <key>acct</key>
                <string>pin</string>
                <key>agrp</key>
                <string>4R7S6N88W9.org.voisine.breadwallet</string>
                <key>cdat</key>
                <date>2015-04-02T02:13:03Z</date>
                <key>data</key>
                <string>**4567**</string>

                <string>mnemonic</string>
                <key>agrp</key>
                <string>4R7S6N88W9.org.voisine.breadwallet</string>
                <key>cdat</key>
                <date>2015-04-02T02:12:10Z</date>
                <key>data</key>
                <string>**finger position giraffe uniform winner mutual profit potato lawn shove amused exit**</string>

                <string>masterpubkey</string>
                <key>agrp</key>
                <string>4R7S6N88W9.org.voisine.breadwallet</string>
                <key>cdat</key>
                <date>2015-04-02T02:12:22Z</date>
                <key>data</key>
                <data>
                **qtsenc3zh0Nf1XwBRYEdxqXkpb4ArOd/UOq9gAcEQFtK198aA1sfSRNBRbBC
                /oiZGWpI3YNtZ6vaa/z6NJMbg3hFg931**
                </data>

Apart from the jailbreak warning when launching, Breadwallet was still fully functional post-jailbreak and the Breadwallet PIN 4567 worked as expected. Not that the PIN really matters, since the attacker has already dumped the recovery phrase so doesn't have any need to actually run Breadwallet on this particular phone.

It would also be possible to create a tweak using the MobileSubstrate framework which would stop the jailbreak warning from appearing or bypass the Breadwallet PIN / TouchID prompts entirely.

I believe this exercise proves once and for all that the Secure Enclave on iPhone 5s and newer does _not_ protect keychain data in the event of a device being jailbroken.

The **only** way to benefit from the Secure Enclave and Touch ID to actually enhance the security of credential storage would be to apply the **kSecAccessControlUserPresence** flag to relevant keychain items. Only those items are encrypted with a key held by the Secure Enclave. Every time such an item is accessed using SecItemCopy(), a valid fingerprint has to be presented or the iOS device passcode has to be re-entered. This cannot be bypassed even on a jailbroken device.

The way in which Breadwallet currently uses TouchID (using the LocalAuthentication framework) is bypassable as it relies on the framework to return a true/false return value which can be spoofed on a jailbroken device.

If LocalAuthentication-based TouchID is preferred for whatever reason that's fine, but let's not pretend that Secure Enclave somehow magically protects keychain data in the event of a jailbreak. This is simply not true. The only way to benefit from TouchID & Secure Enclave is to make use of the kSecAccessControlUserPresence keychain access control flag.

PS - Is there any reason why some Breadwallet keychain entries are stored with WhenUnlockedThisDeviceOnly while others are store with protection class AfterFirstUnlockThisDeviceOnly?

**Comment by JustinDrake** [comment]
@hubert3: Thanks for this investigation. Awesome stuff. I'm building my own iOS wallet, and would be curious to know if you'd be interested in reviewing it (e.g., for security).

**Comment by voisine** [comment]
@hubert3 really appreciate the research. I will also try to duplicate with the new jailbreak tool, and also investigate whether using the user presence access control setting makes a difference.

Out of curiosity, was restoring the phone from an iTunes backup a part of the jailbreak process? It occurs to me that if the secure enclave is wiped, it might then be able to be restored after the jailbreak process from backup.

The problem with using user presence access control is that touch id can't then be optionally disabled over a certain spending limit, leaving the users entire funds open to the fake finger attack.

**Comment by hubert3** [comment]
@voisine No, the phone did not have to be wiped or restored prior to running the TaiG jailbreak. It's possible to jailbreak the phone at any time (if it's running a vulnerable version of iOS) and keychain contents can then be dumped. The Pangu jailbreak has worked for me in the same way on earlier versions of iOS 8.

I believe that the only thing the Secure Enclave secures is the fingerprint data itself (so that the kernel never gets to see it) and keychain items that use user presence.

My fingerprints are still registered and Touch ID works post-jailbreak, so I don't think that jailbreaking wipes anything at all.

**Comment by voisine** [comment]
forgot to mention, some of the keychain items are afterfirstunlock because they are needed to do background network fetching while the device is locked, like the master pub key

**Comment by eragmus** [comment]
@voisine said: "The problem with using user presence access control is that touch id can't then be optionally disabled over a certain spending limit, leaving the users entire funds open to the fake finger attack. We'll have to determine which is the greater risk assuming user presence does what we think."

This seems like an extremely serious error that has been discovered (severe because: jailbreaking is trivial, so if someone knows someone stores bitcoins on another person's breadwallet app, stealing their money is as simple as stealing the phone and jailbreaking it.. plus the other couple simple steps). I have to suggest that what easily takes precedence is the jailbreak attack.

First, the other problem (touch id can't be disabled according to certain limits) is vulnerable to a fake finger attack, as you said. So, the jailbreak attack requires an attacker to steal a phone and jailbreak it (trivial), while the touch id attack requires an attacker to steal a phone and somehow get a high quality finger print of the user. Based on this alone, it seems the jailbreak attack is more easily carried out and thus the higher priority.

Second, the touch id issue could also be solved. Touch id can be removed from the purpose of confirming send transactions, and instead only PIN entry can be used to confirm send transactions.

**Comment by DavidStaron** [comment]
The outcome of @hubert3 's experiment doesn't surprise me, i mean the keychain is encrypted with the iPhone passcode, and the phone is unlocked so of course it can be read... how else could the (any) App read the data?

In my opinion the only solution is stronger passwords instead of the 4 digits, so the recovery phrase / keys can be stored encrypted by the strong password.

I understand if this would not be the default option (to prevent BTC loss for less experienced users), but if at least it would be possible for advanced users to enable a strong password in settings...

**Comment by voisine** [comment]
@eragmus it is not trivial to jailbreak a stolen phone that you cannot unlock. (and if you can unlock it, you don't need to jailbreak it, since many people use the same pin for breadwallet) A fake finger won't help you to jailbreak since a pin code is required at startup.

Also you can't require a pin to access items stored in the keychain. User presence can be either touch id or pin. There's no option provided to require pin only.

@DavidStaron the keychain is encrypted with both the users pin and unique key specific to each device which is why it can't be trivially cracked offline if you get a filesystem dump. Unfortunately using a password doesn't appreciably improve security since an attacker can simply log keys/touches when the user enters their password into the infected device.
