### ISSUE TITLE
Choosing my own backup phrase

### ISSUE THREAD

**Issue by cserb** [voisine/breadwallet#141]
English not being my mother tongue I would like to be able to choose my own, so that I would be able to remember it much easier. This way I would not have to write it down.

**Comment by throughnothing** [comment]
The backup phrase is determined from a pre-set list of words as specified by the BIP 39 specification here: https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

The wordlist is here: https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md

While you may think it would be nice to choose your own words, that would actually be less random, and thus less secure.

**Comment by voisine** [comment]
@cserb please write down your backup phrase and keep it in a safe place. Don't rely on remembering it.

Unfortunately being able to choose your own backup phrase doesn't work for security reasons. It has to be generated in a cryptographically random way. All your private bitcoin keys are generated from this phrase.

**Comment by cserb** [comment]
Fine I see the problem, but even the BIP39 wordlist has different languages. Maybe you want to consider supporting those? Or is it already supported, but in my case I saw an English backup phrase because German is not supported yet?

**Comment by voisine** [comment]
Yes, we will add more language support in future.

**Comment by dabura667** [comment]
@cserb what is your language? Perhaps you can help select a wordlist for your language if there is none yet.

Currently, the only languages on the BIP39 page are:

https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md

1. English
2. Japanese
3. Spanish
4. Chinese (Simplified)
5. Chinese (Traditional)

I also know of a portuguese list which has not been included in BIP main repo, but is in Electrum.

https://github.com/spesmilo/electrum/blob/master/data/wordlist/portuguese.txt

(Please note this wordlist does not contain 2048 words like BIP39 requires.)

If your native language is not one of these, let me know if you can help, and maybe we can work on making a list for your language.

**Comment by cserb** [comment]
@dabura667 my language is German. Let me know how I can help.

**Comment by voisine** [comment]
@cserb it's kind of tedious, but if you can select 2048 of the most common short german words, preferably with unique 4 letter prefixes, we can add german to the list of supported languages for recovery phrases. I did it for english. You might consider starting here: http://en.wiktionary.org/wiki/Wiktionary:Frequency_lists#German

**Comment by dabura667** [comment]
@cserb 

https://docs.google.com/spreadsheets/d/1eeIM2SBadpBYH8hW6fsxUbhrxAKjylMB2DLPbiNPFlk/edit?usp=sharing

I went ahead and made a spreadsheet using the 5000 most common words on German Wikipedia, I removed all words less than 4 letters long, and I added some columns to test uniqueness.

1. It must have exactly 2048 words.
2. Each word should start with a unique set of 4 letters. (basically, in the spreadsheet you want No. of duplicates to be 0. It is counting the number of duplicates of the first 4 letters)
3. Try to pick commonly used memorable words.
4. Just because the word is "Good" on that sheet does not mean it is suitable for BIP39, please think of whether the word is appropriate for the wordlist.

@voisine if you can think of any other criteria that might help in choosing.

@cserb if you can tell me a google account I can invite so I can let you edit the document.
