### ISSUE TITLE
banner notifications

### ISSUE THREAD

**Issue by Rudayb23** [voisine/breadwallet#153]
I seriously love breadwallet it's truly revolutionary. I have a few ideas that would make the app so much better. 

1. Under transaction details, have the "status" box link to blockchain.info

2. Show the current exchange rate on the send page. 

3. Have an option on the "warning your phone is jail broken" to never show up again

4. I know you are so adamant about the bits over btc but can you please throw an option in there for that. Have bits be set by default but have the option to change to btc. 

Thank you,
Rudy bermúdez

**Comment by voisine** [comment]
Thanks for the feedback @Rudayb23, we appreciate it.

Firstly please don't use breadwallet on a jailbroken phone. Any jailbreak app can read your recovery phrase and rob you. It's just as insecure as any desktop or web wallet. Bitcoin stealing malware is already a huge portion of all the malware being discovered and bitcoin is still tiny.

We know it's a pain right now when most people aren't using bits yet, but we want to help push the standard forward. We think it will benefit bitcoin adoption in the long run and make your bitcoin more valuable. Just remember that 1,000,000bits = 1bitcoin, so you can just replace the second coma with a decimal point in your head.

I do think we need to find a more prominent place for the exchange rate. (right now it's only on the local currency setting)

You can tap the txid to copy to clipboard and paste it into other services like blockchain.info. We want to try to keep the app independent of any particular web service as much as possible.

**Comment by Rudayb23** [comment]
Last thing. Is there any way we could get banner push notifications when we receive bitcoin? For example I opened up bread wallet, and then I go to angry birds. My buddy sends me some bits and then I get a banner saying I received some bits

**Comment by voisine** [comment]
It updates the app badge if it finds a new transaction when the app syncs with the bitcoin network in the background, it could also make a banner. The only problem is that you wouldn't see it immediately, it only checks every few hours. We can't send you a remote notification because your wallet is private, so we don't know when you receive money.

**Comment by Rudayb23** [comment]
I would really like the banner notifications even if it is every few hours. That would be amazing.

**Comment by voisine** [comment]
Cool, I was thinking of doing it.

**Comment by Rudayb23** [comment]
You’re an awesome dev for listing to users like me. Can you add your donation address in the about page? I would love to send you some bits.

**Comment by voisine** [comment]
We haven't added a notification banner yet due to privacy concerns. I was thinking we can add it though so long as it's off by default.

**Comment by Logicwax** [comment]
It would be nice to have a banner (and audible notification) for at least a few minutes after closing the app though.    I paid a friend, who has an android phone, the other day.   He showed me the QR-code....then locked his phone and put it in his pocket.   I finished filling out the amount to send, then sent the TX.   I could hear the "coin drop" sound coming from his pocket, letting him know it went through.   Would be nice to have this ability (because I do like the app badge number as well)

**Comment by voisine** [comment]
iOS apps can only run in the background for about 30 seconds after you close them except in special circumstances, like streaming audio. After that, it will get woken up and sync ever several hours, which is when the badge and/or banner would be updated.

**Comment by Logicwax** [comment]
How come iTeleport, prompt (ssh client), and colloquy (IRC client) are able to stay running for 10mins?      ITeleport and Prompt both warn me with a banner notification when 10mins starts to near that it's closing down and going to close the connection to my server.

**Comment by voisine** [comment]
Here's the appropriate documentation: https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html

Interesting, it looks like there's no exact time limit defined, but it used to be 10 minutes when explicitly starting a background task: http://www.raywenderlich.com/92428/background-modes-ios-swift-tutorial

"Previous to iOS 7, apps were given up to 10 continuous minutes to finish whatever they were doing before being truly suspended. With the advent of NSURLSession there is a much more elegant way to handle large network transfers. Because of this, the available background time for arbitrary computation has been reduced to just a few minutes and is no longer necessarily continuous."

The 30 second limit is if you don't start a background task. To be kind to battery life we only start a background task when the wallet isn't yet fully synced.

**Comment by Logicwax** [comment]
I'm seeing breadwallet having no problem updating the badge number, as you said

*iOS apps can only run in the background for about 30 seconds after you close them except in special circumstances, like streaming audio. After that, it will get woken up and sync ever several hours, which is when the badge and/or banner would be updated.*

Well I ONLY see the badge update.  I don't ever see a banner and/or anything appearing on my lockscreen.   There is also no sound either.

**Comment by samuraisam** [comment]
Banners are added in: https://github.com/samuraisam/breadwallet/commit/aa085248342e4180c3cfe447a099dc33249b1560

Badge number is fixed in:
https://github.com/samuraisam/breadwallet/commit/bb9c85075a2f935d7531d1f1896233728992b2e8
