### ISSUE TITLE
Touch ID and Passcode

### ISSUE THREAD

**Issue by eragmus** [voisine/breadwallet#157]
I'm perplexed by the latest update's implementation of Touch ID and PIN code.

I appreciate being able to open the app without any friction (no prompt for Touch ID or PIN), and that the balance is hidden and transactions can't be initiated. However, why is the transaction history visible? That's private information; I definitely would not want someone to be able to glance through my history.

I suggest the following:

1. Prompt for Touch ID to allow access to the app, as a whole. Touch ID takes barely 1 second to complete authentication, so it's essentially friction-less, plus it will protect viewing of things like balance and transaction history. You could still make it operate as 'tap to show balance', to protect privacy of that, but no need to use Touch ID or PIN to protect it. Also, even though Touch ID is less secure than a passcode, by using it in this way you are only protecting the more trivial things.

2. Prompt for passcode, whenever making a (send) transaction. This is the most important thing to protect, so I'd like to be able to protect it with a passcode. Personally, I would never use the new feature to allow transactions (of any amount) without any authentication (and every banking mobile app I've seen uses authentication to get into the app, Touch ID or password -- no finance app allows transactions of any size to be made without authentication).

The benefit to the above is that it's essentially 2FA, since it's something you have (Touch ID - finger) along with something you know (passcode). It also balances security with convenience.

P.S. I'd love to be able to choose a custom length of the passcode, just as Apple allow. i.e. Default is 4 characters, but I'd love to be able to use 10 characters, for example.

P.S.S. For those without Touch ID on their device, you could replace the use of Touch ID, above, with a passcode.

**Comment by NanoAkron** [comment]
I have to agree. I preferred the previous functionality - click to load the app, enter your PIN and start using it. 

It used to behave like my other banking apps, but now appearing to allow me in but not really makes it just a bit strange.

**Comment by voisine** [comment]
I agree it's not as intuitive as it should be. I definitely want people to be able to receive funds without unlocking the app. That's a security issue in itself. I also wanted people to be able to quickly check the status of a transaction also without unlocking, which is why it shows the most recent 5. I'm thinking of changing this to just show any transactions with fewer than six confirmations.

**Comment by chrismarquardt** [comment]
Keeping the history screen under locks would be easy to do if it was finally its own screen and didn't have to share with settings, as proposed in #22 - I love breadwallet and use it all the time, but this has been bugging me from the start. Come on Aaron, you can do it! :)

**Comment by voisine** [comment]
@chrismarquardt you know I love you man! :)

I'm trying to think why I haven't implemented your suggestion. You notice in the new update I moved most of the settings to a new screen under the history screen. I really like just having one button for "everything else" apart from send and receive. 

I originally got the idea from the square app, it has a settings view which included a few recent transactions, and then an option to show the full history, so fewer buttons on the main screen.

**Comment by chrismarquardt** [comment]
Maaaan, you can be stubborn ;) I totally understand your wish to keep
things dead simple. But I think "simple" and "intuitive" are two very
different animals sometimes.

The simplicity you seem to try to achieve (e.g. hide the settings one level
deeper) is backfiring because now you can't lock the history while allowing
access to the settings.

Also I believe the average Joe (e.g. the breadwallet target audience) won't
find this intuitive either. Discoverability could definitely be better.

In my eyes it makes sense to have both: a) the wallet balance and the
transaction history locked behind touchID/pin, while b) having the settings
unlocked and easy to discover.

And the best way to achieve that would be to separate them.

**Comment by nshopik** [comment]
I'm with @chrismarquardt here, since his design actually using common way for many apps on ios to hide lots of selection (swipe to right or pressing special button). So it will no new for ios users.

**Comment by voisine** [comment]
I know I can be stubborn, but I'm really trying not to be on this one. It's just that settings are rarely used, so it seems a waste to create extra buttons on the main screen, or extra steps to get to the history. That and my intuitive dislike of sliding sidebar menus is why I haven't done it yet.

https://lmjabreu.com/post/why-and-how-to-avoid-hamburger-menus/

I agree though that the current situation with unlocking the app is sub-optimal. I don't mind having to unlock to get to settings, that's no big deal. The main concern is being able to quickly check recent transaction status without unlocking, which is why I'm thinking of switching it to show just transactions with fewer than 6 confirmations unless unlocked.

**Comment by nshopik** [comment]
Well settings still could be debatable. 

I've found that buttons send/receive below that @chrismarquardt show in his prototype is more intuitive. Almost everyone who I show breadwallet didn't realize they could swipe left-right to send/receive. So please consider them

**Comment by NanoAkron** [comment]
One other issue I have with the new unlocking functionality is that despite unlocking once, I have to enter my PIN yet again to send a transaction.

Please just give us the one pin to log in and start working, just like banking apps.

**Comment by voisine** [comment]
I could make it so you can send without authenticating if you already entered the pin (or touch id if the spend is below the touch id limit)... I kind of liked the fact that you had to authorize the purchase directly though. The common use case I have is launching the app and scanning a payment qr, you then authorize once to make the payment and you're done.

**Comment by throughnothing** [comment]
One argument for not having to type the pin in again if the app is already 'unlocked', is that for in person transactions, when you're scanning someone's qrcode from their phone/tablet, you may unlock the wallet first, to avoid having to type the pin in again with them watching or close.  Then when it asks again, you risk others seeing you type it in while you're trying to complete a transaction.

**Comment by NanoAkron** [comment]
I treat the app like a banking app - I log in to check my current balance and review my previous transactions, and I make payments to QR codes. All my other banking apps just want me to log in once to do all of that.

**Comment by voisine** [comment]
@NanoAkron since bitcoin is digital cash, we have be a little more careful than a typical banking app. That's why for instance it's important that users to be able to receive without unlocking the app. If they're accepting a payment, the payee could grab the phone. With a banking app, you can just call the bank and have them reverse or block any transactions initiated by the phone thief, but bitcoin is cash.

**Comment by eragmus** [comment]
Just to comment again on this, Aaron, I understand your preference/liking for having to directly confirm the transaction (adds to security!), and I agree with the rationale.

To respond to what @throughnothing said:
- One argument for not having to type the pin in again if the app is already 'unlocked', is that for in person transactions, when you're scanning someone's qrcode from their phone/tablet, you may unlock the wallet first, to avoid having to type the pin in again with them watching or close. Then when it asks again, you risk others seeing you type it in while you're trying to complete a transaction.

This is a concern, and I definitely wouldn't want someone to see my PIN (even a stranger), while I'm entering it to confirm the transaction.

A few ways to perhaps mitigate this problem:
- require 2 factor authentication, perhaps in the form of PIN + TouchID (maybe PIN to open app from the start), then TouchID to make transactions, view balance, etc.
- allow setting a PIN longer than 4 characters (the more characters in the PIN, the less chance someone sees the simple 4 characters that currently make up the PIN)
- incorporate 3 factor authentication by including PIN + TouchID as before, but also by including maybe 'one-touch 2fa' a la Airbitz's new 2fa-integrated-into-the-app approach. I've never seen that approach before, but it seems pretty cool. The nice thing about this is it could be integrated into the TouchID part (so 2fa is occurring automatically as TouchID verification is occurring), so that even for phones without TouchID at least the 2fa occurs (fallback to 2fa instead of 3fa).

How do these options sound?

And for that matter, how is multisig integration (in addition to, or as a replacement for my suggestion for 2fa -- I think TouchID should still be used since it's secure and available, right?) progressing?

Also, any plans to integrate with Ledger hardware wallet (Nano, or Blue)? They seem to have the best approach to hardware wallets that I've seen... and secure element hardware specialized for Bitcoin ultimately would appear to trump even Apple's general purpose secure element. So, integrating somehow with Ledger may be a good approach!

Sorry for bunching up other topics into this post/thread... just obsessed with the mantra of: security, security, security!! :)

**Comment by voisine** [comment]
The idea of not entering your pin to confirm a payment sort of makes sense.

touch id doesn't work 100% so it can never be required, it can only be an option with pin entry as backup.

I do plan to enable longer pin codes.

since touch id doesn't work 100%, we can't really do 3fa, but we have better 2fa than anyone else. you need the phone (something you have) and you need either a thumbprint (something you are) or pin code (something you know). and unlike 2fa web services like airbitz, users aren't subject to man-in-the-middle or phishing attacks or android malware.

multi-sig is on the roadmap, but below a secure android version using TEE.

Ledger and other hardware wallets are using a general purpose secure element, not much different that what's built into iPhone and most android devices, so we'll be focusing on those first since the install base is in the 100's of millions.

**Comment by eragmus** [comment]
Great, thank you, Aaron.

**Comment by UnquietCode** [comment]
I was actually disappointed by the latest update. Now even without a pin my transactions are shown. I consider this sensitive information. The previous version was more protective, even if a bit pedantic.

**Comment by nshopik** [comment]
@UnquietCode its fixed already in master and show only unconfirmed transactions

**Comment by UnquietCode** [comment]
@nshopik Awesome, thank you! It is sometimes hard to tell when something is an intended change or a bug. Thanks for your continued vigilance.

**Comment by voisine** [comment]
The initial issue description is addressed. Only transactions with fewer than 6 confirms are visible without unlocking.
