### ISSUE TITLE
Importing Private Keys

### ISSUE THREAD

**Issue by Rudayb23** [voisine/breadwallet#160]
I have been trying to import a private key into bread wallet and every single time it tells me that the key is empty. The key is in the WIF format. Can I import without sweeping?

**Comment by voisine** [comment]
Do you know the public address for the key? Can you confirm that it has a balance?

**Comment by Rudayb23** [comment]
Yes I can do both.

**Comment by voisine** [comment]
If you're comfortable with it you can email me the public address. Don't send me the private key. My email is in the LICENSE file. I just tested it with a private key myself at it worked for me.

**Comment by Rudayb23** [comment]
Can I import the public address without sweeping it?

**Comment by voisine** [comment]
No, if you scan a public address it assumes you want to send to it.

Also since the wallet is deterministic, all the private keys in the wallet are generated from your recovery phrase. That way all you ever need is the recovery phrase to get everything in your wallet back. If you could import private keys without sweeping, and then lost your phone, you could lose your money since that private key can't be generated from your recovery phrase.

**Comment by Rudayb23** [comment]
That makes so much sense now.

**Comment by iOSDeveloperSK** [comment]
If your app will not be supported in several years or will not be compatible with the new iOS version  how can I access to my funds? Recovery phrase is not good idea, because I can not recover my wallet from another wallet. Every seed is for specific software wallet (seeds from breadwallet are not compatible with electron seeds). Private key is private key.
