### ISSUE TITLE
Slow confirmations due to low fees

### ISSUE THREAD

**Issue by trevorchill** [voisine/breadwallet#168]
I've been experiencing multiple blocks before transactions are confirmed.  This is really inconvenient.  I would gladly add more for transaction fees to get transactions confirmed in the next block.  Could you please add such an option or modify the new fee calculation somehow?  

FYI, I recently sent a transaction for 1 btc that was confirmed only on the fourth block.  I can't wait over an hour for a first confirmation...

**Comment by voisine** [comment]
@trevorchill I'd like to get transactions confirmed as quickly as possible. What use case do you have where you are waiting for the confirmation? The reason I ask is that usually it's the recipient who's concerned about confirmation time, not the sender. When I pay bitpay or coinbase invoices it gets accepted immediately for instance, and always confirms within the next few blocks.

**Comment by voisine** [comment]
We currently always make fees high enough to beat a typical 1 input, 2 output tx (247bytes) with a minimum 10bit fee, which ends up being about 40bits per kb of tx size.

**Comment by trevorchill** [comment]
In many use cases, I need to wait until at least one confirmation before going on to do other things.  In any case, it would solve the problem if we could have a setting to add x bits to the default fee, or something similar.  Then I could try it with an extra 50 bits or 75 until I consistently get into the first block...

**Comment by voisine** [comment]
I don't expect users to wait around for confirmations in most cases, but it would help me to understand what the situations are where actual users are doing this.

Ideally we don't want users to need to understand anything about fees. It should just work, always getting confirmed in next couple of blocks at most, but preferably the next block quite often, with fees automatically set to the minimum needed to make that happen.

We can definitely tweak the fee algorithm to make that that case more consistently. I need to set up some tools to help monitor what fees are being paid and how quickly transactions get confirmed across the bitcoin network.

**Comment by voisine** [comment]
right now the fee we generally add is 11bits for a single input, two output tx. if this were bumped up to 20bits then breadwallet tx would make it into eligius pool for one, and probably other pools with similar fee structures. for larger tx with multiple inputs, just like now, the fee would be higher. basically we'd be nearly doubling the current fees across the board.

curious what people's reaction to that is? does anyone care about paying 1/2 a penny instead of 1/4?

**Comment by nshopik** [comment]
@voisine what about something like smart-fee in bitcoin-core or its not possible since you don't have full blockchain on SPV clients?

**Comment by voisine** [comment]
It has a rough heuristic for dynamic fees now based on the number of transactions in recent blocks, so fees will increase if blocks start to fill up, but since it's not online most of the time it can't observe how long trnasactions take to confirm.

I could run a service that provides that info but we need the app to do a reasonable job without it so it doesn't rely on a service like that.

**Comment by trevorchill** [comment]
No, I agree that a service is not a great idea.  I want a capable standalone wallet.  But I also want to be able to make sure I get a transaction into the next block.  I think this is an instance in which it's worth it to allow power users to set their own transaction fee.  I never had to worry about it before with the standard fee because I always got into the next block, but now, I have a problem because there's no way for me to make sure of that.

You already have a setting to include no fee when allowed, why not just change that so that it asks you for a manual fee entry instead of asking you if you really want to send with no fee?  Or allow us to set a manual default fee in the settings.  

I think that the default should be something that makes sure of inclusion in the next block, maybe double the minimum or somesuch.  But I'd still really like the option to set my own fee if the default doesn't pretty much guarantee inclusion in the next block.

**Comment by voisine** [comment]
We've actually removed the no fee option for the next update since it's become a lot less useful recently with the fee drop and higher transaction volume on the network. Plus it was confusing users.

I'd much rather just get the fees right instead of adding options that users don't understand how to use. Other payment systems that bitcoin has to compete with all have fixed or hidden fees. Choosing the fee yourself requires a lot of intimate knowledge of how the bitcoin network works.

I think I'll go ahead and up the fee to get into eligius pool, since that seems to be the next decent sized jump in confirmation speed, and it's also the only pool I know of that implements child-pay-for-parent so users can spend unconfirmed inputs without putting their confirmed inputs in limbo in the process.

**Comment by traidman** [comment]
Does that mean upping it beyond 11?

**Comment by voisine** [comment]
Yes, it'll be about 20, so right now that's just over 1/2 a penny instead of just over 1/4.
