### ISSUE TITLE
Control the security stack

### ISSUE THREAD

**Issue by jonasschnelli** [voisine/breadwallet#170]
Wouldn't it be possible to completely remove the usage of apples CC (`CommonCrypto/CommonCrypto.h`) and use libsecp256k1 in all places? I didn't had a close look at it.

Pretty impressive work btw. Nice!

**Comment by jonasschnelli** [comment]
Hmm... just saw you usage of `CCHmac` and `CCKeyDerivationPBKDF`, etc.
Closing this because the only substitute would be openssl...

**Comment by voisine** [comment]
Thanks for your interest @jonasschnelli, the most critical security issue is probably the random seed generation, and I believe common crypto may be using the hardware rng in the secure enclave, which would be ideal. Pbkdf2 isn't much of a concern since the results are easy to verify and any deviation will be immediately noticed. (Though it's fair things like constant time execution to avoid side channel attacks are also important to consider)
