### ISSUE TITLE
Import private key by typing

### ISSUE THREAD

**Issue by BladeBronson** [voisine/breadwallet#183]
I just bought a physical Bitcoin in Burnos Aires. The private key is beneath a sticker, but written as a string of numbers and not rendered as a QR code. Can we have an import private key by keyboard?

**Comment by voisine** [comment]
Yes, you can type it in notes or elsewhere and copy it to the clipboard. It will automatically do the right thing if you "pay address from clipboard". It's not very intuitive, but copying a private key to the clipboard isn't the safest since it's visible to other apps, so I didn't want to encourage it. If you kill all the other apps running in the background first I believe it should be safe. Just make sure you transfer the balance before you launch any other apps.
