### ISSUE TITLE
KDF could be improved

### ISSUE THREAD

**Issue by jonasschnelli** [voisine/breadwallet#190]
Currently breadwallet uses SHA512 as KDF at 2048 rounds. IMO this is weak.
It would be nice to have support for `scrypt`.
For SHA512 there should be 25'000 rounds at least.

**Comment by jonasschnelli** [comment]
https://github.com/voisine/breadwallet/blob/master/BreadWallet/BRBIP39Mnemonic.m#L138

**Comment by voisine** [comment]
It's so weak that it might as well not even be there, but it's part of the BIP39 specification unfortunately. The original BIP39 authors wanted something that could be implemented in low power, low memory embedded chips in devices like trezor. 

Since we're not using the password option, and the recovery phrase already has 128bits of entropy, there's no increased security risk at least.

**Comment by jonasschnelli** [comment]
Oh. Right. It's Bip39 standard.
Hmm... the question how much sense it makes to use Bip39 at all.

**Comment by voisine** [comment]
The main worry would be people typing their recovery phrase into other devices and wallets with lower security standards, but since we're not bip44 that helps to mitigate the problem. It feels like a good compromise between protecting users from issues in other wallets and the ability to get funds out if there's ever a problem with breadwallet.
