### ISSUE TITLE
Apple watch support

### ISSUE THREAD

**Issue by gigq** [voisine/breadwallet#191]
Was thinking about trying to write an apple watch extension when mine comes in (mid May).  Wondering if you had any thoughts on what a bread wallet watch app would look like.  I'm thinking a glance to show qr code and balance could be useful.  Not sure if anything else really makes sense vs just using the phone though.

**Comment by losh11** [comment]
I'd think that this would be a cool function - a quick send or quick
receive through the watch.

Quick question - are there any NFC enabled BTC recievers?

**Comment by gigq** [comment]
Unfortunately Apple doesn't open up NFC for developers to use, it's only used by the built in Apple Pay.  If they did ever open that up it would be a great feature for sending payments, or even if they just had a camera on the watch that would be useful but I'm not sure sending would work very well from the watch as it is today.

Receiving via QR code seems like it would work fine though.  I was thinking of QR and balance information in a glance and maybe a list view of transactions in the watch app.  Seems like it would be a quick way to check if a payment was received or check on number of confirmations of a sent payment.

**Comment by Onetallnerd** [comment]
+1. I think circle has an watch app, or one coming too.

**Comment by voisine** [comment]
Would be nice. Off the top of my head I would think it would be similar to the "today" notification center functionality, mainly displaying a QR for receives since launching the phone app from your watch is less useful. It could show notifications for receives, however showing tx history and balance would be problematic since you want the user to authorize that with pin or touch id. Maybe since the watch is more personal, i.e. you won't be lending it to others, then it's less of a concern, you could just authorize the watch from the app one time.

I would just start with the QR, and then move on from there.

**Comment by Onetallnerd** [comment]
The watch has this thing where you could authenticate once with your phone using touch id and everything like tx history would show on the watch until you take the watch off. Once the watch detects that you have taken it off it disables those features.

**Comment by voisine** [comment]
Ah, very nice. That would be the way to do it then.

**Comment by Fogh** [comment]
Once I get my hands on one of those watches, then it would be very cool to have a simple overview of your wallet on the watch.

**Comment by voisine** [comment]
apple watch app is now in the repo
