### ISSUE TITLE
difficulty send funds

### ISSUE THREAD

**Issue by simontsui8** [voisine/breadwallet#221]
I tried to send to 3 different address, all ends up with unconfirmed after about 3 hours and it is still like that.

but amount already taken off the balance.

what should i do?

**Comment by voisine** [comment]
Now that the bitcoin network is reaching capacity, long confirmation times will become much more common. Breadwallet allows you to spend unconfirmed inputs immediately, so this doesn't change day-to-day usability.

The current network congestion is due to the CoinWallet.eu "stress test" (or attack, depending in your point of view)
https://www.reddit.com/r/Bitcoin/comments/3agk61/ultimate_bitcoin_stress_test_monday_june_22nd/

There is code in place for the next app update to allow for dynamic fees based on current network conditions, but the current release doesn't have it yet. By the time an update were to make it through the app store review process (several days), the current abnormal congestion will have passed.

**Comment by simontsui8** [comment]
I see, the problem is the other party always ask for 3 confirmations before
it is showing on balance, so I can send, but they will not confirm they
received it and give me the service or goods I want, is there anything I
can do about it?

**Comment by voisine** [comment]
The other party may decide to change their policy due to current network issues. In theory they might be able to help get the transactions confirmed by re-spending them with higher fees to trigger something called child-pays-for-parrent

**Comment by voisine** [comment]
Actually, some of my test transactions sent with the most recent app store release v0.5.1 went through after about 30min. I think some miners may have started ignoring the coinwallet.eu tx flood. Did your tx confirm?

**Comment by simontsui8** [comment]
No, same as before. But I do have three different responses,

1. Nope, wait!
2. Accepted
3. The other end is another  wallet of mine, it accepted but pending, then
I sent to another wallet , it went through, but all pending status showing

**Comment by voisine** [comment]
looks like your transactions confirmed

**Comment by simontsui8** [comment]
yes, the earliest confirmed, thanks for your help. last question, what happens if people send the money to my old address been used before?

Thanks

**Comment by voisine** [comment]
Your address will change each time you receive funds, but old addresses always work.

**Comment by simontsui8** [comment]
Thank you, have a good day! Great app
