### ISSUE TITLE
Using breadwallet in areas without cell phone coverage

### ISSUE THREAD

**Issue by mgbtcfv** [voisine/breadwallet#225]
I work in a place where cell phone reception is disabled. However there is WiFi which has some type of Firewall, I assume. breadwallet cannot connect to the internet through WiFi. I can not use breadwallet because I get the message that it is not connected. Is this something that can be fixed?

**Comment by dabura667** [comment]
> WiFi which has some type of Firewall

Tell your network admin to open outgoing / incoming connections on port 8333.
Otherwise, I don't know what to tell you... breadwallet is a bitcoin node, and companies want to block any and all unnecessary ports... I think you'll have a hard time convincing your company to open them.

If your company allows VPN connections, you can connect to a VPN via your settings menu and THEN breadwallet should work.

But I'm almost certain your work won't allow VPN connections either...

Even if someone set up a proxy on port 80 (http) somewhere... that is a huge security risk for you, as that user could then feed you false information.

**Comment by voisine** [comment]
@mgbtcfv, there are a few options, one as @dabura667 suggests is to get your company to open the firewall. Since Bitcoin traffic is not encrypted and is verified locally by breadwallet, the only thing a proxy operator can do is exclude transaction info which can be corrected with a rescan later when not using the proxy. This risk is the same as when connecting to someone else's wifi or if your ISP wanted to do this to you. We could set up an (encrypted) proxy ourselves for our users as a last resort.

I'd also like to enable bitcoin to work in places with no cellular data. Merchants can provide wifi but it's an extra step for the user to connect to it. Bitcoin network data could be relayed over  Bluetooth by the merchant terminal for instance, but to support that we'd need to work closely with many bitcoin merchant service providers to create a standard, which we hope to do in the future.

**Comment by mgbtcfv** [comment]
Thank you!
