### ISSUE TITLE
Use recovery phrase multiple times

### ISSUE THREAD

**Issue by eaigner** [voisine/breadwallet#246]
I briefly looked at the source and the app itself and was curious how breadwallet derives it's keys. Usually you can only restore a wallet from a private key once - thus I wondered if I could do it multiple times with the same passphrase in breadwallet (the site isn't too specific on this).

Lets say I created a wallet on phone `A` with recovery phrase `phrase1`. Will I be able to restore the exact same wallet on phone `C` with and `D` with the same phrase `phrase1` without losing anything?

In any case, it seems a clarification on the site / store page would help.

**Comment by voisine** [comment]
Yes, your recovery phrase is all you need to recover you wallet on another device if yours is lost.

The best way to think about it is that your bitcoin is stored securely on the peer-to-peer bitcoin network. Your phone is where the keys are to get access to it. Your recovery phrase is the key. When you type it into a phone, you are making a new copy of the key. You still have strong protection if your phone is stolen because iOS devices are AES hardware encrypted by default.

**Comment by eaigner** [comment]
If the recovery phrase represents my (a single) private key, then this explanation would contradict yours: [Using Paper Wallets](https://www.reddit.com/r/Bitcoin/comments/1c9xr7/psa_using_paper_wallets_understanding_change/). 

What did I miss?

**Comment by eaigner** [comment]
Oh... seems that doesn't apply to deterministic wallets like breadwallet.

**Comment by voisine** [comment]
That's correct.

**Comment by eaigner** [comment]
Thanks for clarifying. Much appreciated!
