### ISSUE TITLE
Libbitcoin will offer "very fast SPV"? Can/Should breadwallet migrate to libbitcoin?

### ISSUE THREAD

**Issue by eragmus** [voisine/breadwallet#250]
Hi,

I'd like to bring attention to this comment, by Airbitz' founder, Paul:
> there are tradeoffs between SPV and supernode wallets but the Libbitcoin project is looking to combine the best of both with a very fast SPV header download protocol that can even go through an encrypted channel while also giving very fast indexed queries. All in a free, open source, supernode server anyone can run. Airbitz already uses Libbitcoin and we look forward to adding this support.

https://www.reddit.com/r/Bitcoin/comments/3etohn/whats_wrong_with_breadwallet/ctirou5

What are the pros/cons of breadwallet shifting development over to libbitcoin, in order to take advantage of fast SPV? One of the most common complaints by users is the "slow" SPV speed, especially for users with poor cellular network connections. The initial syncing that occurs when the app is opened can be burdensome to wait for completion if a user just wants to quickly open the app to make a payment. Thus, it would seem to be advantageous to adopt libbitcoin to get access to quick (nearly instant?) SPV. Due to the structure of libbitcoin, I don't believe the "fast" SPV code can be ported over to Bitcoin Core (which is what breadwallet uses, I think), but correct me if I'm wrong.

Either way, basically I'm curious to know if breadwallet can increase SPV speed, either by the approach that will be used by Airbitz, or via a different approach.

Thanks.

**Comment by voisine** [comment]
Typical sync times are under 2 seconds. We haven't really had any complaints about it. The only time it takes longer is if you kill the app (or reboot your phone) and then don't use the app for weeks or months, so that's probably why we don't get complaints. People who use the app don't see long sync times.

That said, we will want to improve the performance of the protocol for rescans since it will take longer and longer as the wallet gets older. I haven't looked at the libbitcoin protocol, but we'd want to make sure you don't reduce privacy over what you already do with a bloom filter. I envision an improved SPV protocol being something we'd build as a patch on bitcoin core that you'd use automatically if the node you connect to supports it. Hopefully eventually being included in core by default. If we're running nodes to support millions of breadwallet users we'd be sure to enable it on our own nodes.
