### ISSUE TITLE
Moneywagon SPV

### ISSUE THREAD

**Issue by eragmus** [voisine/breadwallet#262]
Please read this:
> https://github.com/priestc/moneywagon/blob/master/whitepaper.md

>> When Satoshi released his bitcoin witepaper in 2009, he included a section called "Simple Payment Verfication". This scheme was a method for building a bitcoin wallet application without needing to keep a local copy of the bitcoin blockchain.

>> I believe Satoshi's scheme was sufficient for the ecosystem that existed at the time, but in 2015 the bitcoin ecosystem has grown by orders of magnitude. With this white paper, I propose another more modern method of architecting lightweight wallets that leveraging the massive bitcoin ecosystem.

How does this sound? Can/should breadwallet adopt it?

Also, please read:
> https://github.com/priestc/moneywagon/blob/master/README.md

>> Moneywagon lets you build a bitcoin wallet application in Python without ever having to rely on a single blockchain API service. This library is both Python 2 and Python 3 compatible.

>> For instance, lets say you are building an application in Python that needs to know the current exchange rate between BTC and USD. Before moneywagon, you had to hardcode your application to make an HTTP request to a single service like bitstamp to get the current price. If the bitstamp API were ever to change, your code would break, wasting development time. With moneywagon, you code your application to the moneywagon API (which doesn't change), and under the hood you can swap between services.

Is this viable? It would seemingly mean not having to rely on a single API service for price data.

**Comment by voisine** [comment]
The author doesn't understand how SPV works, assumes that SPV wallets trust data from untrusted nodes. We're using bitpay for exchange rate data since they're the biggest payment processor. When we pull from multiple sources we'll do it ourselves rather than trusting an aggregator which would not really be any different from trusting a single source.

**Comment by eragmus** [comment]
Thanks Aaron. By the way, Luke Jr made a criticism of SPV, which I'd like you to give your position on, if possible.

I had mentioned to Luke that SPV over Tor would seemingly solve the privacy difference between using SPV vs. using Bitcoin Core wallet, but he wasn't satisfied, saying:
> "SPV" wallets are basically completely insecure

> They essentially operate by trusting random unauthenticated nodes. You might as well be using a webwallet run anonymously over Tor.

**Comment by voisine** [comment]
lukejr says a lot of things. I wouldn't take it too seriously until he explains his reasoning more clearly. I respect his talent and contribution to bitcoin, but I disagree with many of his positions. It's possible that he believes SPV is insecure because it follows the majority of hashing power, and the majority of hashing power might follow consensus rules he disagrees with, but that's only a guess. I can't speak for him.

**Comment by eragmus** [comment]
Good points, thanks, I've requested clarification.
