### ISSUE TITLE
Malleability stress test ongoing...

### ISSUE THREAD

**Issue by eragmus** [voisine/breadwallet#285]
Is breadwallet susceptible?

https://www.reddit.com/r/Bitcoin/comments/3nfb2y/eli5_for_double_spends_bitcoin_being_sent_twice/

This is benign (does not cause loss of funds), but is causing chaos in the Bitcoin ecosystem.

The attacker confessed here:

https://bitcointalk.org/index.php?topic=1198032.msg12579271#msg12579271

**Comment by dabura667** [comment]
> Is breadwallet susceptible?

In theory, no. As breadwallet uses bloom filters which do not rely on txid solely to track transactions.

However, in practice, we can not forsee every possible internet connection configuration for every single device and every possible node that each device could connect to... so I wouldn't say 100% no... maybe just a 90% no.

**Comment by dabura667** [comment]
Actually, there is one way it is affected very much so.

If you spend unconfirmed change (aka send bitcoin multiple times in a row within ten minutes or so) and the first transaction you sent has the altered ID transaction confirmed, then all of your subsequent transactions will be nullified and there is NO WAY to make them valid except for sending the same amounts to the same addresses again.

There is NO way to prepare for that, except by preventing users from spending unconfirmed outputs.

Or coding some automated script that will watch for altered ID transactions being confirmed, and if confirmed, the wallet automatically re-generates the unconfirmed chain that you had originally sent all over again and re-sent it without the user's knowledge in the background.

**Comment by voisine** [comment]
@dabura667 is correct. It get's treated like a second double-spend tx. The user will see the maelated transaction in their history marked as "invalid". Once one or the other confirms, the remaining one will get ejected from mempools on the network and then disappear from the user's history. Their balance will remain accurate throughout.

The problem only occurs if you spend several times in a row without waiting for the earlier spends to confirm, and you don't have enough already confirmed unspent outputs to supply all your spends. In that case, if the maelated version an earlier tx gets confirmed, the subsequent dependent spends will be invalidated and the funds return to the user's wallet.

**Comment by voisine** [comment]
One way to help mitigate, but not eliminate this, is to start splitting change if the user has fewer than, say, 10 unspent outputs (but probably only of the change is also at least twice the size of the spend). 

The network will in future also limit the length of unconfirmed chains to mitigate various potential mempool attacks, so this will be useful even after BIP62 is deployed.

**Comment by eragmus** [comment]
FWIW, Taariq mentioned an idea, which got a good response from a couple others:
> https://twitter.com/taariqlewis/status/651192505606639616

**Comment by voisine** [comment]
Yes, this is something I was thinking about as well. It only works if low/high-s value is the only thing being modified, and it won't work for transactions you receive from others that are part of a chain, since you can't publish multiple versions of their transactions to you, but it would help for chains you create yourself by spending unconfirmed change.

**Comment by eragmus** [comment]
FYI, Greg Maxwell proposed the following to fix the narrow case of low-/high- S attack, and it seems to have consensus:
> https://github.com/bitcoin/bitcoin/pull/6769

**Comment by voisine** [comment]
That is an elegant fix. Just malleate all tx to the canonical form before relaying. We won't be affected since we're already conforming.

**Comment by eragmus** [comment]
:+1: 

I suppose BIP 62 will eventually fix the rest of the diverse malleability possibilities, and that just needs to be awaited.

By the way! I was requested by Mark Friedenbach to ask you to review this idea, to get your feedback. Basically, Mark is worried about pushback from infrastructure developers because they would have to update their code. Are the benefits worth it though, to outweigh the costs?
> https://www.reddit.com/r/Bitcoin/comments/3ngtx5/could_the_segregated_witness_part_of_the/cvol46y?context=4

The whole thread, really, would be good to read.

**Comment by voisine** [comment]
If the network moves in this direction, we will of course support it, but I'm very skeptical a hard forking change like this will get wide support. I'm not one who thinks we should cram everything we can into a hard fork because there are few opportunities. That's not how to safely upgrade systems. Instead you make changes as simple as possible and apply them one at a time. This also makes any particular change more likely to be accepted. By piling them on you make the whole thing less likely to be accepted. However, I suppose American porkbarrel politics are a counter example to this. When a bill is sure to pass, everyone rushes in to tack on funding for their own pet projects.

**Comment by voisine** [comment]
Re: porkbarrel politics, I don't think the analogy applies on further thought. It would be quite difficult for anyone to modify a given hard fork proposal after it becomes clear that it will succeed.

**Comment by eragmus** [comment]
From what I understand, the proposed 'Segregated Witness' is a single technological change. The idea is that it offers only benefits and no downsides, one benefit being no more malleability (of any variant, I think). It is a single change, in other words. Mark did allude to other things, but those things are not part of the hard fork proposal he was throwing out there. I'm sure the other things can be independently discussed and if consensus exists, merged in a piecemeal fashion.

**Comment by maaku** [comment]
@voisine the problem is that many hard forks by themselves are not by themselves important enough to warrant going through the difficulty of a hard fork. Take for example the time warp attack -- why hasn't this been fixed? It's been known about for years and bitcoin still remains vulnerable. For many of these uncontroversial-on-their-merits changes, an omnibus hard fork is the only reasonable way to expect them to ever be deployed. (Before anyone argues that hard forks should be easier to pull off, or more frequent, that in itself poses an existential risk to Bitcoin. Pulling off an arbitrary change to the underlying rules of Bitcoin _should_ be hard, or else Bitcoin is not adversarially secure.)

Segregated Witness is a simple change, conceptually. It is just unfortunately a very deep change that modifies the observed behaviour of higher layers in the application stack. What SW does is change the way transactions are hashed when constructing the transaction Merkle tree such that signatures are not included. So the txid doesn't include the signatures (malleability fixed) and the block itself doesn't contain the signatures either (signatures don't even have to be downloaded e.g. during IBD of old blocks, or within SPV proofs).

I think I can confidently say that if Satoshi knew what we know now, Bitcoin would have had SW from day one. Just like if he had known about the time-warp issue he wouldn't have released Bitcoin with that particular off-by-one error. However unlike time-warp, SW does impact a lot of infrastructure if we were to change to it today. In particular it means txids will be calculated different (how much code uses txids? just about all the code out there), and SPV proofs would be different, since signatures would no longer be included but carried out of band. That impacts a lot of infrastructure, but probably SPV wallets the most. My question to @eragmus which he carried here was: are the advantages of segregated witness clear enough that we can count on support not pushback from infrastructure developers (e.g. you)? If so, we could start an effort to get SW scheduled for deployment. I just don't want to pick a battle with entrenched interests against us :)

**Comment by voisine** [comment]
@maaku I appreciate the advantages. Clearly including the signatures in the transaction hashes (and hence the merkle root and block hashes) was an unfortunate design that we would choose to do differently if we had it to do over. As I mentioned, if that hard fork gets wide support, we will of course implement the change and release an update. This will still result in problems though. There are many users who will have the app on an old phone turned off and secreted away, who will be quite surprised to pull it out of storage one day, plug it in, and find they can't send coins until they perform an app update. Many other wallets will have the same issue. Having to update all bitcoin software in existence, and then get those updates deployed to 100% of users is a *huge* downside that I think you may be underestimating. I really quite like g.maxwell's solution of just having full nodes maleate all tx to a canonical form before relaying. Simple, effective, non-disruptive, instantly deployable, only really requires a few mining pool operators to put it into effect. I wouldn't give pushback to SW, but I wouldn't advocate for it either. I think there are other options with better cost/benefit tradeoffs.

**Comment by eragmus** [comment]
So, with the latest news re: Segregated Witness, what is your latest view, @voisine? Do you advocate the soft-fork approach, or are you willing to reverse the previous stance and advocate hard-fork approach?

[side note: Gavin posted to bitcoin-dev in support of SW, but preferring a hard fork.]

**Comment by voisine** [comment]
I haven't read gavin's post yet, but I'm excited by all the stuff we can get into the protocol via soft fork using this method, and it should be much easier to get consensus around it. Since it would only apply to addresses that chose to use the SW addresses, we should still have full nodes auto-maleate all classic transactions.

**Comment by jonasschnelli** [comment]
related: http://bitcoinstats.com/irc/bitcoin-dev/logs/2015/12/08#l1449595219.0
