### ISSUE TITLE
BIP-70 bug (?)

### ISSUE THREAD

**Issue by AndersBNielsen** [voisine/breadwallet#292]
I was just testing if Breadwallet supports BIP-70 with Coinify(.com)

It seems to work protocol-wise but when making the payment Breadwallet doesn't seem to register the amount and I have to manually enter it. 
After making the payment the status is "Payment received" in Breadwallet which could confuse people whether they sent or received a payment. Status should probably be "Payment received by merchant".

I can't seem to figure out if this is a Breadwallet-bug or a Coinify-bug... (The QR data looks correct)

Payment-QR attached.

![coinifyqr](https://cloud.githubusercontent.com/assets/7676834/10535732/9bece7ae-73e5-11e5-955d-cd7c20273761.png)

**Comment by voisine** [comment]
the qr contains: bitcoin:1MC9MVJSWYXDYXGqWMzwYV9i5VzBEoi2gd?amount=0.00006000&r=https://www.coinify.com/pr/Ue/OA9b

This returns a bip70 payment request with an amount field of 0, which is why breadwallet requested you enter an amount. That doesn't match the amount listed in the qr, so I'm guessing it's a coinify bug.
