### ISSUE TITLE
Custom transaction descriptions?

### ISSUE THREAD

**Issue by mortengh** [voisine/breadwallet#303]
The transaction log quickly gets very long an looking back, a month or two, and I have no idea what the transactions was about. Would it be possible to be able to, in a simple way, map a transactionid to one line of text like in a printout from the bank.
I understand that syncing this over multiple devices is a problem because that would require a central server but just have it (encryptet) in a mapping file on the device and being able to import/export it (still encryptet) would be very usefull.

**Comment by voisine** [comment]
We do plan to add transaction metadata. As you point out, this information wouldn't be in the blockchain, which is why we haven't done it yet. We'd encrypt the data so that only someone with the recovery phrase would be able to decrypt it, but persistent cloud storage is a problem. We could use iCloud, but we want something that will work on android as well, and also ideally that doesn't require username/password.

duplicate #86
