### ISSUE TITLE
Jailbroken phone > wallet deleted

### ISSUE THREAD

**Issue by netsmashers** [voisine/breadwallet#355]
After installing breadwallet on an jailbroken iPhone, the app gave a warning. After clicking "ignore" the wallet vanished and the app started with the initial screen (New wallet / recover wallet). From a usability standpoint this is very weird. 

Is there a way to recover the wallet after this incident? Is the original wallet seed stored on the phone somehow? Or is this wallet lost forever?

Thanks.

**Comment by voisine** [comment]
Sorry for the late response. If you click "ignore", it should continue normally, however the default button is "wipe" to remove your sensitive recovery phrase from the compromised device, as any app you install can steal your funds otherwise. You may have tapped "wipe" inadvertently. I will modify it so that it sends you to the recovery phrase screen to copy down your phrase if you haven't done so yet, instead of presenting a wipe option. It would be better if the wipe option were only the default if you've previously indicated that you wrote down your recovery phrase.

**Comment by voisine** [comment]
this is fixed by 9805ce5
