### ISSUE TITLE
Transactions being broadcast are not hitting the required fees for it to be picked up and confirmed by miners.

### ISSUE THREAD

**Issue by SCDeveloper** [voisine/breadwallet#357]

**Comment by SCDeveloper** [comment]
I thought Breadwallet used "adaptive" fees? I have gotten close to changing the code and jailbreaking my iPhone lol

**Comment by voisine** [comment]
No need to jailbreak, anyone can install from source using Xcode and their iTunes account as of iOS 8.

Breadwallet is currently paying just over 26 satoshis per byte, which the 21.co fee API says is above the minimum for a 90% chance of confirming within an hour.

Our own testing confirms this. Do you have a stuck transaction? Maybe you are spending an unconfirmed receive that paid low or no fee? We use CPFP to get these unstuck by it can take a while since CPFP is only supported by a small number of miners yet.

**Comment by SCDeveloper** [comment]
I have attempted to send to the same address a lot of times. But each time I have sent I have waited and then just recovered the wallet and resynced. So I am not double spending. I just get unverified. Over and over.

**Comment by voisine** [comment]
Do you have the latest version 0.5.4? It sounds like a tx missing rather than a fee issue. Contact support@breadwallet.com if the issue persists

**Comment by SCDeveloper** [comment]
Yeah latest from the app store. I will contact support@breadwallet.com to see what they can do ;)
