### ISSUE TITLE
Rescan blockchain replaced with swipe-down gesture?

### ISSUE THREAD

**Issue by kwolk** [voisine/breadwallet#361]
Is there a need to have a "rescan blockchain" button if minimalism is the goal, when it's perfectly natural for iOS users to drag the screen down to refresh a page?

If you think that "Go" style button (which browser designers insisted on to execute the text inside a URL address field once upon a time) is still necessary on an iDevice then fine, but why not have the hidden option for those who are used to gestures as they take up no extra screen real estate?

**Comment by voisine** [comment]
Pull-to-refresh is typically for quick, lightweight operations that take a few seconds at most. A blockchain rescan is a heavy operation that can take many minutes for older wallets. We want to warn users about this by having a description of when to use it and how long it takes.

In future updates we hope to be able to move it off the transaction history and burry it further under settings so people aren't tempted to use it just because it's there, only if they really do think they may have connected to a malicious peer on the bitcoin network that has omitted some of their transactions.
