### ISSUE TITLE
Transactions do not show the year they took place

### ISSUE THREAD

**Issue by kode54** [voisine/breadwallet#369]
I have a history of transactions that cut off at May 5th, presumably 2015, followed by the next two or three transactions, which take place in the preceding December.

It's kind of hard to keep track of when these happened, since the history does not display a year, only the month, day, and approximate time.

**Comment by dabura667** [comment]
I agree.

Perhaps the year could be shown as a small 2 digit number next to transactions which are not in the current year? 2015 would be 15 etc.

**Comment by voisine** [comment]
Anything over 12months old does include the date, at least for the US locale. The December tx are from 2014 then, and don't show the year?

**Comment by kode54** [comment]
Maybe they're from December of 2015. The only thing that made me think they were any older is that the most recent transaction is currently permanently locked to the current time because it's stuck "unverified". I made the mistake of thinking I somehow made that transaction exactly a year ago, because it happened at least enough time ago that I forgot when.

**Comment by dabura667** [comment]
I just confirmed that all transactions before May 5th 2015 have 15/05/02 etc. with the year next to it.

**Comment by losh11** [comment]
I don't know if I'm using a old version of the app, but can we have accurate transaction times? On my device and simulator in transaction history I only see something like 12/23. Instead of that, can we have something like 20:32 16/12/16.

Also, not sure if this is a bug or not. My device is set as UK, but the dates are written in US locale.

**Comment by voisine** [comment]
You definitely want to make sure you've got the current version. 0.5.4

It's doesn't list the to time down to the minute since the only timestamps recorded in the blockchain are the confirmation times. It shows just the hour of the day since confirmation times are typically several minutes after the txt was actually sent.

If you've been using an old version of the app that used checkpoints to estimate the time instead of the actual block timestamp, then you can fix that by doing a blockchain rescan after updating the app.

**Comment by kode54** [comment]
It's a transaction that's still showing as "Unverified" so it continues to show the current date and time. I guess I could try building my own that points to my own personal server, but that means I'll have to bootstrap a new Bitcoin node.

**Comment by voisine** [comment]
That shouldn't be needed. Would you be interested in getting on our testflight program? If so you can send your iTunes email address to support@breadwallet.com. We can try out a potential fix.

**Comment by kode54** [comment]
I already just got in, and successfully synchronized that transaction away. It took place in January.
