### ISSUE TITLE
Question about lock icon (TouchID)

### ISSUE THREAD

**Issue by ffxsam** [voisine/breadwallet#370]
Could someone explain what the lock icon is supposed to do? It seems useless. I tap it, and then I'm prompted for my fingerprint. Why? If I quit BreadWallet and open it again, I would expect to be asked for my fingerprint, but I'm taken right into the app. I don't really find this to be too secure.

**Comment by voisine** [comment]
The lock icon reveals your balance and transaction history. It's useful to be able to launch the app and show the receive screen to someone without revealing your wallet balance.

On the send screen you can initiate a transaction, and you will be required to supply a fingerprint or passcode in order to complete it.

After launching the app, the sending funds or any action that would reveal sensitive information requires authorization with fingerprint or passcode, so the app is secure, but you can still use the app without authorizing for actions that don't require it, such as receiving.
