### ISSUE TITLE
Wallet recovery from lost phone

### ISSUE THREAD

**Issue by ffxsam** [voisine/breadwallet#371]
I'm new to Bitcoin, so bear with me..

If I lose my iPhone, assuming the thief is not able to get into my phone at all and spend my cash, I can use my recovery phrase on a new phone to recover my cash, correct? How exactly does that work, on a technical level??

**Comment by dabura667** [comment]
> on a technical level??

1. The phrase you are given has a 4 bit checksum encoded in it to prevent incorrect phrase inputs.
2. Your phrase is hashed after NFKD normalization using PBKDF2 with 2048 iterations on SHA512 with a dkLen of 64 and a salt value of "mnemonic". This gives the same 64 bytes of psuedo-random data for each phrase.
3. The 64 bytes are fed into BIP32 seeding algorithm which uses HMAC-SHA512 with the salt of "Bitcoin seed" to generate a separate 64 byte psuedo-random sequence which is split into two chunks of 32 bytes, one for the master private key, and one for the chain code which is used to further ensure the entropy of index values when deriving keys.
4. The Master Private key then uses BIP32 to derive a path of m/0'/0/0 to get your first address / private key pair, m/0'/0/1 to get your second, and so on and so forth.

As you can see, since everything is a hash algorithm, it's all one way, and the same input will always get the same results in the end.

Your 12 word phrase contains 128 bits of entropy, which is the maximum amount of security possible with secp256k1 on the elliptic curve.

**Comment by ffxsam** [comment]
Ok, I can see how the phrase translates into hashes. But what I don't get is if I have 3 BTC in my wallet and I lose my phone, how is a pass phrase (set of hashes and possibly my keys) going to know how much I had in my wallet?

**Comment by dabura667** [comment]
> how is a pass phrase (set of hashes and possibly my keys) going to know how much I had in my wallet?

A passphrase can't *know* anything. It doesn't have memory or a CPU to remember or think, as it is just a set of words. I think you're trying to ask a different question.

If you have a key, you can ask nodes on the bitcoin network to tell you about related transactions and calculate your balance from that.

Restoring a wallet on breadwallet takes usually about 5-10 minutes to get up to date. This is because it asks the network about all your addresses.

**Comment by ffxsam** [comment]
The question I'm asking is, if I have 3 BTC on my phone, and that's lost, BreadWallet makes it sound like I can install it on a new phone and recover my 3 BTC. How does that mechanism work?

**Comment by dabura667** [comment]
>The question I'm asking is, if I have 3 BTC on my phone, and **that**'s lost,

What's "that" referring to?

> BreadWallet makes it sound like I can install **it**

What is "it" referring to?

> on a new phone and recover my 3 BTC.

-------

> How does that mechanism work?

I explained above. A chain of varioud hashing algorithms.

> Where is that data stored, exactly?

While your app is working properly, the phrase is stored in the secure enclave of the APU in your phone.

If you destroy your phone, but still have your phrase written down on a piece of paper somewhere, you can just install breadwallet on another device and enter the same phrase and all your bitcoins, addresses, and history will be there.

If you don't understand my explanation, I can't help you anymore, I'm sorry.

**Comment by voisine** [comment]
@ffxsam I think I understand your question.

You bitcoin is not stored on your phone. It is stored in the eternal blockchain on bitcoin peer-to-peer network. The only thing on you phone is a "key" that you use to prove to the bitcoin network that those funds belong to you.

Your recovery phrase is that master key. All the individual keys for each of the bitcoin address in your wallet can be created from the master key. The app then simply connects to the bitcoin network and "syncs" (asks the bitcoin network how much bitcoin belongs to your addresses) and show you how much money you have control over in the bitcoin network.

**Comment by ffxsam** [comment]
Thanks @voisine! I eventually figured this out. So all the "cash" is stored on the blockchain (is this essentially similar to public torrent trackers?), and the private keys are used to access said cash.

**Comment by voisine** [comment]
It is very similar, except far more robust and reliable than torrent trackers. There are many thousands of peer-to-peer nodes, each with a complete copy of the blockchain (the giant ledger of which addresses own which coins). All the nodes on the network reach agreement with each other and they all check each other's work to prove nobody is cheating. Breadwallet does the same, it is a peer on the network and checks to make sure the rest of the network agrees that money you receive really exists and wasn't already sent to someone else.
