### ISSUE TITLE
Implement Touch ID as alternative to PIN codes

### ISSUE THREAD

**Issue by nshopik** [voisine/breadwallet#39]
These guys seems wrote working code https://github.com/chain-engineering/chain-ios-wallet-demo for Touch ID

**Comment by hubert3** [comment]
+1 for this enhancement.

Touch ID can add security even on jailbroken devices.

Implementing TouchID by calling the LocalAuthentication framework adds no real security as it returns a simple true/false value from the fingerprint check which can easily be tampered with (MobileSubstrate tweak, cycript etc)

However, applying the new access control flag **kSecAccessControlUserPresence** to the keychain item means that every time anything tries to access that item (whether Breadwallet or a keychain dumping utility), the user will be prompted to provide a valid fingerprint OR re-enter the device passcode. 

This can't be bypassed as even the kernel itself doesn't have the key to decrypt the item before valid auth is provided (this makes use of the "secure enclave").

See https://developer.apple.com/library/ios/samplecode/KeychainTouchID/Introduction/Intro.html for a code sample.

The one caveat is that re-entering the device passcode is always available as a fallback to providing a fingerprint. However, on iPhone 5s/6 devices where the user uses Touch ID to unlock the device, it's practical to set a long and strong device passcode as you rarely have to enter it.

I would suggest making an option available on Touch ID that applies **kSecAccessControlUserPresence** to the existing keychain items Breadwallet uses, as an extra security measure in addition to the Breadwallet PIN (not instead of it).

**Comment by billinghamj** [comment]
If this isn't added, I will fork, add the functionality and make the build available as an external testflight beta.

**Comment by voisine** [comment]
@hubert3 I had originally implemented using keychain access control, but switched to local authentication so I could implement a spending limit after which the pin is required. With keychain access control there is no way to force pin entry to defend against the fake finger attack.

I don't think keychain access control provides significant additional security since malware targeting jailbroken breadwallets can just replace breadwallet with a malicious version that waits for the user to authorize a spend and then steals the seed.

**Comment by hubert3** [comment]
I noticed after writing the comment above that there was already some Touch ID code in BRWalletManager.m.

I have to read up more on how Breadwallet actually works and makes use of Keychain, but if important keys are secured with kSecAccessControlUserPresence I think that would make it harder for malware to do anything. The Touch ID prompt would appear whenever anything tries to SecItemCopy the relevant items. That would be very suspicious if it happened out of the blue while the user wasn't interacting with Breadwallet. Malware would have to hook the legitimate Breadwallet process, wait for the user to interact with it and steal data at the point just after the user has authenticated with fingerprint or device PIN.

This is harder to achieve and will take longer than in the current situation where malware can dump all of Breadwallet's keychain data at any time, silently in the background.

**Comment by voisine** [comment]
@hubert3 any malware would have to jailbreak the phone or only target already jailbroken phones to get the keychain.

If targeting breadwallet on jailbroken devices, it would be a simple matter to just replace the breadwallet binary with a slightly modified version that would only present the user with the touchid prompt when they expect it, but then send the seed to the attacker.

**Comment by voisine** [comment]
@hubert3 by using local authentication we get the very real security improvement of defending against the fake finger attack by forcing pin entry over a certain amount.

**Comment by voisine** [comment]
implemented and working well in master

**Comment by billinghamj** [comment]
Do you have a release scheduled for this?
