### ISSUE TITLE
Lost iPhone but have a full iTunes backup

### ISSUE THREAD

**Issue by rvanbaalen** [voisine/breadwallet#391]
How can I recover my wallet? I have a full backup of my iPhone on my computer made with iTunes.
However the iPhone itself is no longer accessible and I dont (!!!) have my passphrase.

Can I somehow track back what my wallet address was and simply access it by using my password? I do remember the password by I'm guessing I need some sort of waller regeneration as well? Can I retrieve that data from the iTunes backup?

**Comment by rvanbaalen** [comment]
I have managed to extract the Sqlite database from the iTunes backup. Is there somebody able to recreate the application data with that table?

**Comment by voisine** [comment]
@rvanbaalen I'm sorry, to keep your funds secure, it's designed so that you need either the device the wallet was created with, or the recovery phrase.

The master private key is encrypted with the secure enclave, so the iTunes or iCloud backup of the key can only be decrypted with the device it was made from. This way if an attacker is able to get your backups, they can't steal your money.

**Comment by rvanbaalen** [comment]
Sorry to abuse the issue tracker for this if you want We can discuss this over email. 

I do actually still have the original device. So recovering the itunes backup to that device might work you say?

**Comment by voisine** [comment]
It should, yes. You can contact support@breadwallet.com if it doesn't work as expected.

**Comment by dabura667** [comment]
> I have a full backup of my iPhone on my computer made with iTunes.

Was the "encrypted backup" checkbox checked?

If yes, your keychain is in the backup.

If no, your bitcoins are gone... sorry.
