### ISSUE TITLE
Keychain seed / private keys protection

### ISSUE THREAD

**Issue by IpsmLorem** [voisine/breadwallet#397]
I'm wondering about the seed / private keys protection inside the keychain.

According to iOS Security guide, one can :

`Keychain access control
Keychains can use access control lists (ACLs) to set policies for accessibility and
authentication requirements. Items can establish conditions that require user presence
by specifying that they can’t be accessed unless authenticated using Touch ID or by
entering the device’s passcode. [...]`

What about enforcing that ACL to increase security instead of your own PIN number ?

Furthermore :

`[...] Access to items can also be limited by specifying that
Touch ID enrollment has not changed since the item was added. This limitation helps
prevent an attacker from adding their own fingerprint in order to access a keychain
item. `

May be interesting but the user must be warned at the seed creation.

**Comment by voisine** [comment]
We use the "while unlocked, this device only" ACL

The problem with the user presence option is that there's no way to require the user to enter their passcode for larger amounts, so using that alone would expose funds to the "fake finger" attack. (your fingerprints are all over the phone) That's why we have a separate app passcode that gets requested when your cumulative spending exceeds the touch id spending limit in settings.
